/**
 * ─────────────────────────────────────────────────────────────────────────
 *  THE ONLY FILE YOU NEED TO EDIT TO CHANGE THE WEDDING DETAILS.
 * ─────────────────────────────────────────────────────────────────────────
 *
 *  Everything the invitation shows - names, parents, dates, venue, photos,
 *  music, RSVP number - is read from here. No component hardcodes any of it.
 *
 *  Fields written as "ADD ..." are intentional placeholders: replace the text
 *  and the site picks it up. Photo paths point at /public/images/... - drop
 *  files with those names in and they appear automatically; until then an
 *  ornamental frame is shown in their place.
 */

export const weddingConfig = {
  /** The couple together — shown in a single frame in the "Beloved" scene. */
  couplePhoto: "/images/couple/couple.jpeg",

  groom: {
    name: "Kirana K R",
    shortName: "Kirana",
  },

  bride: {
    name: "Anusha T S",
    shortName: "Anusha",
  },

  wedding: {
    /** ISO 8601 with the India offset - drives the countdown. */
    dateISO: "2026-09-10T10:10:00+05:30",
    dayName: "Thursday",
    dateLabel: "10 September 2026",
    /** Malayalam calendar date shown alongside, as in the reference card. */
    malayalamDate: "Chingam 25, 1202",
    time: "10:10 AM — 10:50 AM",
    muhurthamNote:
      "The groom's party leaves at 8:45 AM. Solemnised according to traditional Kerala Hindu rituals within the auspicious muhurtham.",
    ceremony: "Wedding Ceremony",
    venue: "AL Saj Convention Centre",
    address: "Vellayani, Nemom, Thiruvananthapuram, Kerala",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=AL+Saj+Convention+Centre+Vellayani+Nemom+Thiruvananthapuram",
  },

  contact: {
    /** Digits only with country code, e.g. "919876543210". Currently unused —
        kept for a future RSVP or "message us" link. */
    whatsapp: "",
  },

  music: {
    enabled: true,
    /** Drop your track at public/music/wedding.mp3 - control appears regardless. */
    source: "/music/wedding.mp3",
  },

  gallery: [
    { src: "/images/gallery/couple-main.jpg", alt: "Kirana and Anusha together" },
    { src: "/images/gallery/moment-02.jpg", alt: "The couple during their pre-wedding shoot" },
    { src: "/images/gallery/moment-03.jpg", alt: "Kirana and Anusha hand in hand" },
    { src: "/images/gallery/moment-04.jpg", alt: "A candid moment between the couple" },
    { src: "/images/gallery/moment-05.jpg", alt: "The couple in traditional attire" },
  ],

  site: {
    url: "https://kiranaanusha.vercel.app",
    /* Share card is generated by src/app/opengraph-image.tsx. */
  },
} as const;

export type WeddingConfig = typeof weddingConfig;
