/**
 * ─────────────────────────────────────────────────────────────────────────
 *  THE ONLY FILE YOU NEED TO EDIT TO CHANGE THE WEDDING DETAILS.
 * ─────────────────────────────────────────────────────────────────────────
 *
 *  Everything the invitation shows - names, parents, dates, venue, photos,
 *  music, RSVP number - is read from here. No component hardcodes any of it.
 *
 *  Fields written as "ADD ..." are intentional placeholders: replace the text
 *  and the site picks it up. Photo paths point at /public/images/... - drop
 *  files with those names in and they appear automatically; until then an
 *  ornamental frame is shown in their place.
 */

export const weddingConfig = {
  /** The couple together — shown in a single frame in the "Beloved" scene. */
  couplePhoto: "/images/couple/couple.jpeg",

  groom: {
    name: "Kirana K R",
    shortName: "Kirana K R",
  },

  bride: {
    name: "Anusha T S",
    shortName: "Anusha T S",
  },

  wedding: {
    /** ISO 8601 with the India offset - drives the countdown. */
    dateISO: "2026-08-31T10:00:00+05:30",
    dayName: "Monday",
    dateLabel: "31 August 2026",
    /** Set the muhurtham time here; it also drives the countdown above. */
    time: "9:30 AM to 10:30 AM",
    ceremony: "Wedding Ceremony",
    venue: "Maatha Convention Hall, KB Cross, Tiptur Taluk, Tumkur District",

    /** The celebrations, in order. Add or remove entries freely. */
    events: [
      {
        name: "Reception",
        dayName: "Sunday",
        dateLabel: "30 August 2026",
        time: "From 7:00 PM onwards",
      },
      {
        name: "Wedding Ceremony",
        dayName: "Monday",
        dateLabel: "31 August 2026",
        time: "9:30 AM to 10:30 AM",
      },
    ],
    address: "Bengaluru, Karnataka",
    mapsUrl: "https://maps.app.goo.gl/f3JYBa2PGtV6b1jo7",
  },

  contact: {
    /** Digits only with country code, e.g. "919876543210". Currently unused —
        kept for a future RSVP or "message us" link. */
    whatsapp: "",
  },

  music: {
    enabled: true,
    /** Background track for the invitation. */
    source: "/music/marriagesong.mp3",
  },

  gallery: [
    { src: "/images/gallery/couple-main.jpg", alt: "Kirana and Anusha together" },
    { src: "/images/gallery/moment-02.jpg", alt: "The couple during their pre-wedding shoot" },
    { src: "/images/gallery/moment-03.jpg", alt: "Kirana and Anusha hand in hand" },
    { src: "/images/gallery/moment-04.jpg", alt: "A candid moment between the couple" },
    { src: "/images/gallery/moment-05.jpg", alt: "The couple in traditional attire" },
  ],

  site: {
    url: "https://kiranaanusha.vercel.app",
    /* Share card is generated by src/app/opengraph-image.tsx. */
  },
} as const;

export type WeddingConfig = typeof weddingConfig;
